apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: always-firing-alert
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: test.alert.rules
      rules:
        - alert: AlwaysFiringTest
          expr: vector(1)
          for: 0s
          labels:
            severity: warning
          annotations:
            summary: "Always firing test alert"
            description: "이 알람은 항상 활성화됩니다. 메일 수신 테스트용입니다."
